### ISSUE TITLE
HELLO FRIEND, GREAT JOB I HAVE THIS PROBLEM.

### ISSUE THREAD

**Issue by edwardes2201** [GNSSOEM/ELT_RTKBase#13]
STARTING SERVICES
################################
Job for gpsd.service failed because the control process exited with error code.
See "systemctl status gpsd.service" and "journalctl -xeu gpsd.service" for details.
################################
END OF INSTALLATION
You can open your browser to http://192.168.1.174 fd61:698d:f941::585 fd61:698d:f941:0:de4b:526b:c2cf:5d82 2803:9810:619d:d600:91dc:10e8:99fb:4895 
################################
################################
DELETE GARBAGE
################################
You can open your browser to http://rtkbase.local into local network
edward@rtkbase:~/Downloads/ELT_RTKBase-1.7.5 $

**Comment by edwardes2201** [comment]
![Image](https://github.com/user-attachments/assets/26af7435-3226-4763-86c1-616f84fe3a25)

**Comment by Jef239** [comment]
Unfortunately, you did not send the entire log from install.sh. Can you send it?

One of the reasons is that the antenna is not connected or the antenna is in the room.

**Comment by BONGDV** [comment]
I also encountered a similar case with the UM982 module with firmware UM982_R4.10Build13495, there was no signal when the coordinates entered into the main service were more than 300m from the current position of Rtkbase, no RTCM3 data was output. The solution is to enter the coordinates that are close to the current Rtkbase point.

![Image](https://github.com/user-attachments/assets/57794ba8-37d4-450a-a36a-86e4d4883dd0)

**Comment by BONGDV** [comment]
Strange, this problem does not exist on rtkbase 2.6.3, but it exists on ELT_RTKBase, how to fix it Admin?

**Comment by Jef239** [comment]
> Strange, this problem does not exist on rtkbase 2.6.3, but it exists on ELT_RTKBase, how to fix it Admin?

Test more thoroughly. This problem is in the receiver, not in rtkbase or ELT_RTKBase.

ELT_RTKBase can fix it, but only in the situation when coordinates are set in the receiver from the Web GUI.
https://github.com/GNSSOEM/ELT_RTKBase/blob/main/Install/UnicoreSetBasePos.sh#L290

rtkbase, most likely, does not know how to set coordinates in the receiver at all. Instead, it replaces coordinates in RTCM3 1005/1006 at the str2str settings level. Which, in my opinion, gives less measurement accuracy compared to setting coordinates in the receiver.

**Comment by BONGDV** [comment]
Same hardware: Raspberry Pi4, Unicore Um980 module connected via UART, I installed rtkbase 2.6.3 and there is no problem with Status service when entering coordinates on Web GUI.
ELT_RTKBase is perfect but Status service does not work when entering coordinates on Web GUI further from the receiver's calculation point. I am a practitioner, not a programming expert so I don't know where the problem is.

**Comment by Jef239** [comment]
> I installed rtkbase 2.6.3 and there is no problem with Status service when entering coordinates on Web GUI.

I repeat once again that there are no problems, because rtkbase by @Stefal does not enter coordinates into the receiver, but replaces them in the RTCM3 stream.

> Status service does not work when entering coordinates on Web GUI further from the receiver's calculation point.

I checked, you are right. It worked before, but broke. Actually, it worked by replacing the exact coordinates with "MODE BASE 1 TIME 60 1" and setting the main service status to yellow.

I wonder who broke it, me or Unicore. The check worked based on the fact that with incorrect coordinates, Uncicore displayed "Position not correct". So either the message is not displayed in the R4.10Build17548 firmware or it is not checked for me.

> I am a practitioner, not a programming expert so I don't know where the problem is.

There is a "View" button for viewing service logs. There are a lot of interesting things there. But this time it is empty.

Ok, I included the bug in the work plan.

**Comment by Jef239** [comment]
Fixed . https://github.com/GNSSOEM/ELT_RTKBase/commit/211126b1fbe0dc925158445909652fdf9933d76a

**Comment by edwardes2201** [comment]
Gracias, lo instalé de nuevo ya aparecen las barras de estado de los satélites en la GUI web. Seguire probando la aplicación. Saludos.

**Comment by edwardes2201** [comment]
Hola amigo, estado probando la aplicación, ys aparecen los satélites, pero cuando le conecto a ntrip caster no se activa en servicio.

![Image](https://github.com/user-attachments/assets/2e0c316a-3ebe-4363-afe9-2c58057fe69a)

![Image](https://github.com/user-attachments/assets/c84b8b81-1aaf-4634-9417-4e336c8a6215)

![Image](https://github.com/user-attachments/assets/25ad5221-fb26-4514-81f3-cf88d6aef0fd)

![Image](https://github.com/user-attachments/assets/49bb6187-210c-4b8b-879a-b0f988e79fb5)

![Image](https://github.com/user-attachments/assets/91e6094c-8c80-444e-bbad-483a5cace1bf)

**Comment by edwardes2201** [comment]
Volviendo a compilar:

![Image](https://github.com/user-attachments/assets/f7e5a3e8-f006-4684-a9c7-9e0188deba5a)

**Comment by edwardes2201** [comment]
Hi friend. I reinstalled everything and now the Ntrip connection works. But I still can't download the Rinex files; the download option isn't activated. Greetings and thanks for your reply.



![Image](https://github.com/user-attachments/assets/27018d1c-6a12-4dc9-a8de-ef62388222e3)

[str2str_file.service.zip](https://github.com/user-attachments/files/19678189/str2str_file.service.zip)

**Comment by Jef239** [comment]
Looks like a bug. I'll check what's going on.

**Comment by Jef239** [comment]
![Image](https://github.com/user-attachments/assets/be36a57a-f733-458d-9516-6727580169ac)

This is not a bug, this is a feature! :-)

It says "raw file archive (zip)". That is, only ZIPs are converted. You need to wait until the day is up and RTCM3s are packed into ZIP. And only after that - convert ZIP to RINEX.

If this is not convenient in some scenario, then describe such a scenario. And it would be better to duplicate [the author](https://github.com/Stefal/rtkbase/issues) the original rtkbase, maybe he will do it faster.
